In [1]:
import numpy as np
import pandas as pd
import chronos
import os
import reportlab
from matplotlib import pyplot as plt
import seaborn as sns
from taigapy import default_tc as tc

In [ ]:
new_directory_path = "D:/Documents/Jayden Chronos test"

os.chdir(new_directory_path)

print(os.getcwd())

In [6]:
readcounts = pd.read_csv('Lenka_TKOv3_screen.count.txt', sep = '\t')
print(readcounts)

                                   sgRNA      Gene  DivCtl_A  Dropout_rep1_B  \
0        chr19:48547138-48547157_CABP5_+     CABP5       650             563
1           chr19:5827797-5827816_NRTN_+      NRTN       744             676
2          chr1:42922341-42922360_PPCS_-      PPCS       731             503
3      chr1:45965068-45965087_CCDC163P_+  CCDC163P       631             509
4        chr7:126173794-126173813_GRM8_-      GRM8       229             303
...                                  ...       ...       ...             ...
71085   chr13:46619542-46619561_ZC3H13_-    ZC3H13         0               0
71086    chr6:37787767-37787786_ZFAND3_-    ZFAND3         0               0
71087   chr19:44636016-44636035_ZNF225_+    ZNF225         0               0
71088   chr16:30794826-30794845_ZNF629_+    ZNF629         0               0
71089  chr7:149152556-149152575_ZNF777_+    ZNF777         0               0

       Dropout_rep2_C  Dropout_rep1_D  Dropout_rep2_E  Dropout_rep1_F1  \
0                1080            1214             829              259
1                1399            1959             620             1054
2                1149             897             673              279
3                 907            1085             915              332
4                 244             411             324              122
...               ...             ...             ...              ...
71085               0               0               0                0
71086               0               0               0                0
71087               0               0               0                0
71088               0               0               0                0
71089               0               0               0                0

       LD20_rep1_F2  LD90_rep1_F3  ...  LD90_rep1_L3  Dropout_rep2_M1  \
0               316            23  ...            17              104
1              1065           200  ...            40               86
2               308            40  ...            74                0
3               369            19  ...            21               92
4               133            34  ...            10               20
...             ...           ...  ...           ...              ...
71085             0             0  ...             0                0
71086             0             0  ...             0                0
71087             0             0  ...             0                0
71088             0             0  ...             0                0
71089             0             0  ...             0                0

       LD20_rep2_M2  LD90_rep2_M3  Dropout_rep1_N1  LD20_rep1_N2  \
0               395             4              121             0
1               226            30              694           351
2                73             3              183            40
3               295             6              380           155
4                31             4               87             8
...             ...           ...              ...           ...
71085             0             0                0             0
71086             0             0                0             0
71087             0             0                0             0
71088             0             0                0             0
71089             0             0                0             0

       LD90_rep1_N3  Dropout_rep2_O1  LD20_rep2_O2  LD90_rep2_O3
0                 0              198           205             0
1                14                1            51             0
2                25                0            51             0
3                17               19           227             0
4                 0               41             6             0
...             ...              ...           ...           ...
71085             0                0             0             0
71086             0                0             0             0
71087             0                0             0             0
71088             0                0             0             0
71089             0                0             0             0

[71090 rows x 37 columns]

In [7]:
guide_map = readcounts[['sgRNA', 'Gene']]
guide_map = guide_map.rename(columns={'sgRNA': 'sgrna', 'Gene': 'gene'})
guide_map[:4]

                               sgrna      gene
0    chr19:48547138-48547157_CABP5_+     CABP5
1       chr19:5827797-5827816_NRTN_+      NRTN
2      chr1:42922341-42922360_PPCS_-      PPCS
3  chr1:45965068-45965087_CCDC163P_+  CCDC163P

In [8]:
sequence_map = pd.read_csv('sequencemap.csv')
print(sequence_map)
sequence_map[:5]

     sequence_ID cell_line_name  pDNA_batch  days
0    noT_day05_1       RKI1_noT           0     5
1    noT_day05_2       RKI1_noT           0     5
2    noT_day15_1       RKI1_noT           0    15
3    noT_day15_2       RKI1_noT           0    15
4    noT_day20_1       RKI1_noT           0    20
5   LD20_day20_1      RKI1_LD20           0    20
6   LD90_day20_1      RKI1_LD90           0    20
7    noT_day20_2       RKI1_noT           0    20
8   LD20_day20_2      RKI1_LD20           0    20
9   LD90_day20_2      RKI1_LD90           0    20
10   noT_day26_1       RKI1_noT           0    26
11  LD20_day26_1      RKI1_LD20           0    26
12  LD90_day26_1      RKI1_LD90           0    26
13   noT_day26_2       RKI1_noT           0    26
14  LD20_day26_2      RKI1_LD20           0    26
15  LD90_day26_2      RKI1_LD90           0    26
16   noT_day31_1       RKI1_noT           0    31
17  LD20_day31_1      RKI1_LD20           0    31
18  LD90_day31_1      RKI1_LD90           0    31
19   noT_day31_2       RKI1_noT           0    31
20  LD20_day31_2      RKI1_LD20           0    31
21  LD90_day31_2      RKI1_LD90           0    31
22   noT_day36_1       RKI1_noT           0    36
23  LD20_day36_1      RKI1_LD20           0    36
24  LD90_day36_1      RKI1_LD90           0    36
25   noT_day36_2       RKI1_noT           0    36
26  LD20_day36_2      RKI1_LD20           0    36
27  LD90_day36_2      RKI1_LD90           0    36
28   noT_day41_1       RKI1_noT           0    41
29  LD20_day41_1      RKI1_LD20           0    41
30  LD90_day41_1      RKI1_LD90           0    41
31   noT_day41_2       RKI1_noT           0    41
32  LD20_day41_2      RKI1_LD20           0    41
33  LD90_day41_2      RKI1_LD90           0    41
34          day0           pDNA           0     0

   sequence_ID cell_line_name  pDNA_batch  days
0  noT_day05_1       RKI1_noT           0     5
1  noT_day05_2       RKI1_noT           0     5
2  noT_day15_1       RKI1_noT           0    15
3  noT_day15_2       RKI1_noT           0    15
4  noT_day20_1       RKI1_noT           0    20

In [9]:
df = readcounts.transpose()
df.columns = df.loc['sgRNA']
df = df.drop('sgRNA')
df = df.drop('Gene')
divctl_a_row = df.loc['DivCtl_A']
df = df.drop('DivCtl_A')
df = df.append(divctl_a_row)
df.iloc[:4, :3]

C:\Users\Jayden MSI\AppData\Local\Temp\ipykernel_10700\1045947000.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(divctl_a_row)

sgRNA,chr19:48547138-48547157_CABP5_+,chr19:5827797-5827816_NRTN_+,chr1:42922341-42922360_PPCS_-
Dropout_rep1_B,563,676,503
Dropout_rep2_C,1080,1399,1149
Dropout_rep1_D,1214,1959,897
Dropout_rep2_E,829,620,673

In [10]:
df.index = sequence_map['sequence_ID'].values
readcounts = df
readcounts.columns = [''] * len(readcounts.columns)
readcounts.columns = guide_map['sgrna'].values

readcounts.iloc[:37, :3]

,chr19:48547138-48547157_CABP5_+,chr19:5827797-5827816_NRTN_+,chr1:42922341-42922360_PPCS_-
noT_day05_1,563,676,503
noT_day05_2,1080,1399,1149
noT_day15_1,1214,1959,897
noT_day15_2,829,620,673
noT_day20_1,259,1054,279
LD20_day20_1,316,1065,308
LD90_day20_1,23,200,40
noT_day20_2,215,461,164
LD20_day20_2,304,312,135
LD90_day20_2,13,53,0
noT_day26_1,117,1226,190
LD20_day26_1,49,1036,266
LD90_day26_1,41,82,66
noT_day26_2,140,190,42
LD20_day26_2,247,103,32
LD90_day26_2,21,37,23
noT_day31_1,83,895,162
LD20_day31_1,89,1139,250
LD90_day31_1,22,99,59
noT_day31_2,76,92,14
LD20_day31_2,332,132,38
LD90_day31_2,20,21,15
noT_day36_1,161,1120,215
LD20_day36_1,40,604,143
LD90_day36_1,17,40,74
noT_day36_2,104,86,0
LD20_day36_2,395,226,73
LD90_day36_2,4,30,3
noT_day41_1,121,694,183
LD20_day41_1,0,351,40
LD90_day41_1,0,14,25
noT_day41_2,198,1,0
LD20_day41_2,205,51,51
LD90_day41_2,0,0,0
day0,650,744,731

In [ ]:
common_essentials = pd.read_csv("D:/Documents/Jayden Chronos test/RKI1_positivecontrol_genes.csv")["gene"]
nonessentials = pd.read_csv("D:/Documents/Jayden Chronos test/RKI1_negativecontrol_genes.csv")["gene"]

positive_controls = guide_map.sgrna[guide_map.gene.isin(common_essentials)]
negative_controls = guide_map.sgrna[guide_map.gene.isin(nonessentials)]

negative_controls.head(10)

In [12]:
sequence_map['sequence_ID'] = sequence_map['sequence_ID'].astype(str)
sequence_map['cell_line_name'] = sequence_map['cell_line_name'].astype(str)
sequence_map['pDNA_batch'] = sequence_map['pDNA_batch'].astype(str)

guide_map['sgrna'] = guide_map['sgrna'].astype(str)
guide_map['gene'] = guide_map['gene'].astype(str)

readcounts = readcounts.astype(float)

positive_controls = positive_controls.astype(str)
negative_controls = negative_controls.astype(str)

In [13]:
print(readcounts.dtypes)
print(guide_map.dtypes)
print(sequence_map.dtypes)
print(positive_controls.dtypes)
print(negative_controls.dtypes)

chr19:48547138-48547157_CABP5_+      float64
chr19:5827797-5827816_NRTN_+         float64
chr1:42922341-42922360_PPCS_-        float64
chr1:45965068-45965087_CCDC163P_+    float64
chr7:126173794-126173813_GRM8_-      float64
                                      ...
chr13:46619542-46619561_ZC3H13_-     float64
chr6:37787767-37787786_ZFAND3_-      float64
chr19:44636016-44636035_ZNF225_+     float64
chr16:30794826-30794845_ZNF629_+     float64
chr7:149152556-149152575_ZNF777_+    float64
Length: 71090, dtype: object
sgrna    object
gene     object
dtype: object
sequence_ID       object
cell_line_name    object
pDNA_batch        object
days               int64
dtype: object
object
object

In [14]:
chronos.nan_outgrowths(readcounts=readcounts, guide_gene_map=guide_map,
                                   sequence_map=sequence_map)

calculating LFC
finding maximum LFC calls
filtering
finding second highest LFC calls
finding sequences and guides with outgrowth
NAing 26253 readcounts (0.01055 of total)

In [44]:
reportdir = "D:/Documents/Jayden Chronos test/reports"

In [54]:
from chronos import reports
print(dir(reports))
print(reports.__file__)

['Image', 'PCA', 'PageBreak', 'Paragraph', 'ParagraphStyle', 'Patch', 'SimpleDocTemplate', 'Spacer', 'TA_JUSTIFY', 'Table', 'UMAP', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'adjustText_present', 'adjust_text', 'all_replicate_plot', 'append_to_legend_handles', 'auc', 'auroc', 'binplot', 'calculate_fold_change', 'check_integration_mean_deviation', 'check_integration_umap', 'comparative_qc_report', 'control_histogram', 'copy_number_gene_corrs', 'copy_number_trend', 'dataset_qc_report', 'density_scatter', 'dict_plot', 'expression_addiction_volcano', 'fast_cor', 'fast_cor_core', 'fdrcorrection', 'gene_corr_vs_mean', 'gene_corr_vs_mean_diff', 'gene_outlier_plot', 'generate_powerset_palette', 'getSampleStyleSheet', 'get_aligned_mutation_matrix', 'get_naive', 'group_cols_with_same_mask', 'guide_estimate_corr_vs_guide_efficacy_scatter', 'guide_estimate_corr_vs_sd_scatter', 'guide_lfc_plot', 'guide_palette', 'hsv_to_rgb', 'identify_outliers_by_diagonal', 'identify_outliers_by_trend', 'identify_outliers_by_zscore', 'inch', 'interrogate_gene', 'interrogate_gene_compare', 'letter', 'lfc_corr_vs_excess_variance', 'load_chronos_data_for_qc', 'lowess_trend', 'mad', 'mean_collapse_dataframes', 'mean_vs_cell_eff_correlation', 'mean_vs_sd_scatter', 'nnmd', 'normalize_readcounts', 'np', 'np_cor_no_missing', 'os', 'pDNA_plot', 'paired_pDNA_plots', 'pd', 'pearsonr', 'plt', 'powerset', 'pr_auc', 'precision_recall_curve', 'predicted_vs_observed_readcounts', 'qc_compare_plot', 'qc_initial_data', 'read_hdf5', 'replicate_plot', 'reportlab', 'rgb_to_hsv', 'roc_auc_score', 'screen_nnmd_auroc_scatter', 'selective_mutated_vs_not_scatter', 'single_line_interrogation', 'sns', 'split_color', 'trim_overlapping_lead_and_tail', 'umap_present', 'warn']
D:\Anaconda\Lib\site-packages\chronos\reports.py

In [ ]:
from chronos import reports
metrics = reports.qc_initial_data("Initial QC", readcounts, sequence_map, guide_map, 
        negative_controls, positive_controls,
                  directory=reportdir
       )

calculating replicate correlation
generating control separation metrics
Plotting log fold-change distribution
plotting control separation metrics

D:\Anaconda\Lib\site-packages\statsmodels\nonparametric\smoothers_lowess.py:227: RuntimeWarning: invalid value encountered in divide
  res, _ = _lowess(y, x, x, np.ones_like(x),

In [17]:
model = chronos.Chronos(
    readcounts={'TKOv3': readcounts},
    sequence_map={'TKOv3': sequence_map},
    guide_gene_map={'TKOv3': guide_map},
    negative_control_sgrnas={'TKOv3': negative_controls}
)

normalizing readcounts


Finding all unique guides and genes
found 71090 unique guides and 18056 unique genes in TKOv3
found 71090 unique guides and 18056 unique genes overall

finding guide-gene mapping indices

finding all unique sequenced replicates, cell lines, and pDNA batches
found 34 unique sequences (excluding pDNA) and 3 unique cell lines in TKOv3
found 34 unique replicates and 3 unique cell lines overall

finding replicate-cell line mappings indices

finding replicate-pDNA mappings indices


assigning float constants
Estimating or aligning variances
	Estimating excess variance (alpha) for TKOv3
Between 327 (batch=Index(['TKOv3_0'], dtype='object')) and 327 (batch=Index(['TKOv3_0'], dtype='object')) negative control sgRNAs were found to be systematically over- or under-represented in the screens and excluded.
Creating excess variance tensors
	Created excess variance tensor for TKOv3 with shape [34, 1]
initializing graph

building gene effect mask

building doubling vectors
made days vector of shape [34, 1] for TKOv3

building late observed timepoints
	built normalized timepoints for TKOv3 with shape (34, 71090) (replicates X guides)

building t0 reads


Building variables

building t0 reads estimate
made t0 batch with shape (1, 71090) for TKOv3
building guide efficacy
built guide efficacy: shape [1, 71091]
building growth rate
built growth rate: shape {'TKOv3': [3, 1]}

building cell line efficacy
built cell line efficacy: shapes {'TKOv3': [3, 1]}
building screen delay
built screen delay
building gene effect
built core gene effect: 3 cell lines by 18056 genes


Connecting graph nodes in model

building effective days
built effective days, shapes {'TKOv3': [34, 18056]}

building gene effect growth graph nodes
built gene effect growth graph nodes, shapes {'TKOv3': [3, 18056]}

building combined efficacy
built combined efficacy, shape {'TKOv3': [3, 71090]}
built expanded combined efficacy, shapes {'TKOv3': [34, 71090]}

building growth estimates of edited cells and overall estimates of fold change in guide abundance
built growth and change

building unnormalized estimates of final abundance
built unnormalized abundance

building normalized estimates of final abundance
built normalized abundance


Building all costs

assembling guide efficacy regularization
building smoothed regularization

building t0 reads regularization/cost

building NB2 cost
building other regularizations

Creating optimizer
initializing variables
estimating initial screen efficacy and gene effect
	 TKOv3
	verifying graph integrity
verifying user inputs
verifying variables
verifying calculated terms
	TKOv3 _gene_effect
	TKOv3 _selected_efficacies
	TKOv3_predicted_readcounts_unscaled
	TKOv3 _predicted_readcounts
	TKOv3 _normalized_readcounts
	TKOv3 _cost_presum
sess run
	TKOv3 _cost
	TKOv3 _full_costs
ready to train

In [16]:
model.train(801, report_freq=50, burn_in_period=50, ge_only=0)

NB2 cost 0.7109600450271177
Full cost 0.7186423822848433
relative_growth_rate
	TKOv3 max 1.022, min 0.98127
mean guide efficacy 0.9920498882042186
t0_offset SD: [('TKOv3', 6.658353222865374e-05)]

gene mean 0.19685162394494424
SD of gene means 0.24240836786837794
Mean of gene SDs 0.163639891139063



51 epochs trained, time taken 0:01:18, projected remaining 0:19:11
NB2 cost 0.5095313515039108
Full cost 0.5371450484502264
relative_growth_rate
	TKOv3 max 1.119, min 0.77951
mean guide efficacy 0.894141891129872
t0_offset SD: [('TKOv3', 0.14975547009521936)]

gene mean 0.1672621699291901
SD of gene means 0.19519138284582593
Mean of gene SDs 0.07867089824367542



101 epochs trained, time taken 0:02:31, projected remaining 0:17:29
NB2 cost 0.48470853469410224
Full cost 0.5072057644632861
relative_growth_rate
	TKOv3 max 1.015, min 0.96927
mean guide efficacy 0.7865645436901888
t0_offset SD: [('TKOv3', 0.13656873276384407)]

gene mean 0.11291119207499178
SD of gene means 0.206362742402335
Mean of gene SDs 0.06478938809180278



151 epochs trained, time taken 0:03:45, projected remaining 0:16:09
NB2 cost 0.48074559063540373
Full cost 0.5029896330173149
relative_growth_rate
	TKOv3 max 1.024, min 0.95223
mean guide efficacy 0.7591202075975365
t0_offset SD: [('TKOv3', 0.1342821359174241)]

gene mean 0.11688119324422193
SD of gene means 0.2104539524336826
Mean of gene SDs 0.06529367211520054



201 epochs trained, time taken 0:04:57, projected remaining 0:14:47
NB2 cost 0.47853813437637815
Full cost 0.5007183750602863
relative_growth_rate
	TKOv3 max 1.025, min 0.95140
mean guide efficacy 0.7371908718438156
t0_offset SD: [('TKOv3', 0.13267675298945147)]

gene mean 0.12242711696084967
SD of gene means 0.21254279214426436
Mean of gene SDs 0.06576243357892697



251 epochs trained, time taken 0:06:10, projected remaining 0:13:31
NB2 cost 0.4770731766748747
Full cost 0.4992572120437025
relative_growth_rate
	TKOv3 max 1.025, min 0.95063
mean guide efficacy 0.7204429931326488
t0_offset SD: [('TKOv3', 0.13167765767625914)]

gene mean 0.126171974091844
SD of gene means 0.21445350217473924
Mean of gene SDs 0.06623506706331658



301 epochs trained, time taken 0:07:23, projected remaining 0:12:16
NB2 cost 0.47618487695723727
Full cost 0.49830962738665224
relative_growth_rate
	TKOv3 max 1.027, min 0.94860
mean guide efficacy 0.7077718259067385
t0_offset SD: [('TKOv3', 0.13075956081642837)]

gene mean 0.1280716994998724
SD of gene means 0.2154245369493809
Mean of gene SDs 0.06654964262788725



351 epochs trained, time taken 0:08:36, projected remaining 0:11:02
NB2 cost 0.4755078480522143
Full cost 0.4976965588718509
relative_growth_rate
	TKOv3 max 1.027, min 0.94851
mean guide efficacy 0.697782422477927
t0_offset SD: [('TKOv3', 0.13046091622519457)]

gene mean 0.12974046025869476
SD of gene means 0.2159759402989612
Mean of gene SDs 0.06688348034482888



401 epochs trained, time taken 0:09:48, projected remaining 0:09:47
NB2 cost 0.4749224038758237
Full cost 0.49707815481625417
relative_growth_rate
	TKOv3 max 1.026, min 0.94920
mean guide efficacy 0.6901078485403713
t0_offset SD: [('TKOv3', 0.12992667729782523)]

gene mean 0.13064353834912673
SD of gene means 0.2165120786205888
Mean of gene SDs 0.06691670933852396



451 epochs trained, time taken 0:11:01, projected remaining 0:08:33
NB2 cost 0.4745754273997077
Full cost 0.4967522993831203
relative_growth_rate
	TKOv3 max 1.026, min 0.94849
mean guide efficacy 0.6839034956898431
t0_offset SD: [('TKOv3', 0.12969112493739973)]

gene mean 0.13126890430403915
SD of gene means 0.21691830401953416
Mean of gene SDs 0.06718788127024733



501 epochs trained, time taken 0:12:14, projected remaining 0:07:19
NB2 cost 0.47431470483050114
Full cost 0.49652221422056286
relative_growth_rate
	TKOv3 max 1.027, min 0.94817
mean guide efficacy 0.6785928562668203
t0_offset SD: [('TKOv3', 0.12953479586091274)]

gene mean 0.1319735757172265
SD of gene means 0.21706727111389257
Mean of gene SDs 0.06728901601445383



551 epochs trained, time taken 0:13:26, projected remaining 0:06:06
NB2 cost 0.47417683126556726
Full cost 0.4964227365604593
relative_growth_rate
	TKOv3 max 1.027, min 0.94745
mean guide efficacy 0.6742505126086358
t0_offset SD: [('TKOv3', 0.12953613959397106)]

gene mean 0.13164137022240233
SD of gene means 0.21727768872944017
Mean of gene SDs 0.06732769054873329



601 epochs trained, time taken 0:14:39, projected remaining 0:04:52
NB2 cost 0.47399482350336286
Full cost 0.4962571756610247
relative_growth_rate
	TKOv3 max 1.029, min 0.94681
mean guide efficacy 0.670392525199102
t0_offset SD: [('TKOv3', 0.1293965203666392)]

gene mean 0.13210649189663143
SD of gene means 0.21757970606140972
Mean of gene SDs 0.06735472515155586



651 epochs trained, time taken 0:15:55, projected remaining 0:03:40
NB2 cost 0.4737698226014679
Full cost 0.4960283916297953
relative_growth_rate
	TKOv3 max 1.027, min 0.94835
mean guide efficacy 0.667396543005895
t0_offset SD: [('TKOv3', 0.1292065685651516)]

gene mean 0.13261929900003527
SD of gene means 0.2178801211300903
Mean of gene SDs 0.06764612058026194



701 epochs trained, time taken 0:17:08, projected remaining 0:02:27
NB2 cost 0.47367406909128146
Full cost 0.4958777367571785
relative_growth_rate
	TKOv3 max 1.027, min 0.94766
mean guide efficacy 0.6645182476606435
t0_offset SD: [('TKOv3', 0.12888038784685077)]

gene mean 0.13266888034457328
SD of gene means 0.21783032031815788
Mean of gene SDs 0.06764481378353417



751 epochs trained, time taken 0:18:21, projected remaining 0:01:13
NB2 cost 0.4735572568830033
Full cost 0.49585226676661825
relative_growth_rate
	TKOv3 max 1.027, min 0.94819
mean guide efficacy 0.6623299556986988
t0_offset SD: [('TKOv3', 0.12914299596559145)]

gene mean 0.13275291604278897
SD of gene means 0.21819746486504005
Mean of gene SDs 0.06770163189345713



801 epochs trained, time taken 0:19:33, projected remaining 0:00:00
NB2 cost 0.4736133217200629
Full cost 0.49592150860933737
relative_growth_rate
	TKOv3 max 1.027, min 0.94757
mean guide efficacy 0.6603849983530105
t0_offset SD: [('TKOv3', 0.12911365325223864)]

gene mean 0.13259936986558013
SD of gene means 0.21776802230276807
Mean of gene SDs 0.06774745809668231

In [17]:
savedir = "D:/Documents/Jayden Chronos test/CRISPR_run"

if not os.path.isdir(savedir):
    os.mkdir(savedir)
    
model.save(savedir, overwrite=True)

print("Saved files:\n\n" + '\n'.join(['\t' + s for s in os.listdir(savedir)
                if s.endswith("csv")
                or s.endswith("hdf5")
                or s.endswith("json")
                ]))

Saved files:

	cell_line_efficacy.csv
	cell_line_growth_rate.csv
	gene_effect.hdf5
	guide_efficacy.csv
	library_effect.csv
	parameters.json
	screen_delay.csv
	screen_excess_variance.csv
	t0_offset.csv
	TKOv3_guide_gene_map.csv
	TKOv3_negative_control_sgrnas.csv
	TKOv3_predicted_lfc.hdf5
	TKOv3_predicted_readcounts.hdf5
	TKOv3_readcounts.hdf5
	TKOv3_sequence_map.csv

In [21]:
gene_effect = model_restored.gene_effect
guide_efficacy = model_restored.guide_efficacy

gene_effect.iloc[:4, :5]

gene                A1BG      A1CF       A2M     A2ML1   A3GALT2
cell_line_name
RKI1_LD20       0.389507  0.217222  0.125577  0.352046  0.227646
RKI1_LD90       0.388702  0.262055  0.172853  0.337187  0.213263
RKI1_noT        0.386804  0.284675  0.193628  0.316670  0.305889

In [24]:
print(nonessentials)
print(common_essentials)

0         MCOLN1
1          PRPH2
2          ACTA1
3          GPSM3
4       C19orf33
          ...
3296        GJB5
3297    C11orf94
3298     SLITRK6
3299       FGF20
3300        SYT9
Name: gene, Length: 3301, dtype: object
0        AAMP
1       ABCE1
2      ACTL6A
3       ACTR8
4        AHCY
        ...
318    ZBTB11
319     ZC3H8
320     ZMAT2
321    ZNF207
322    ZNF622
Name: gene, Length: 323, dtype: object

In [25]:
gene_effect -= gene_effect.reindex(columns=nonessentials).median(axis=1).median()
gene_effect /= gene_effect.reindex(columns=common_essentials).median(axis=1).abs().median()
print(gene_effect)

gene                A1BG      A1CF       A2M     A2ML1   A3GALT2    A4GALT  \
cell_line_name
RKI1_LD20       0.525413  0.092516 -0.137762  0.431286  0.118706 -0.427280
RKI1_LD90       0.523391  0.205165 -0.018971  0.393950  0.082567 -0.652999
RKI1_noT        0.518621  0.262002  0.033230  0.342396  0.315307 -0.559249

gene               A4GNT      AAAS      AACS     AADAC  ...    ZWILCH  \
cell_line_name                                          ...
RKI1_LD20      -0.136292  0.131931 -0.454620  0.056006  ...  1.064447
RKI1_LD90      -0.138587  0.277746 -0.092725 -0.057632  ...  0.255564
RKI1_noT       -0.042232  0.107664  0.045443  0.418631  ...  0.623480

gene               ZWINT      ZXDA      ZXDC    ZYG11A    ZYG11B       ZYX  \
cell_line_name
RKI1_LD20      -0.016545 -0.260068 -0.401529 -0.148308  0.214845  0.136744
RKI1_LD90      -0.204930 -0.041537 -0.218274 -0.174674  0.202745  0.153242
RKI1_noT        0.115777 -0.672122  0.152448 -0.109188  0.108402  0.324298

gene               ZZEF1      ZZZ3  luciferase
cell_line_name
RKI1_LD20       0.479266 -1.671247    0.490876
RKI1_LD90       0.063136 -1.264286    0.392155
RKI1_noT        0.203047 -1.355150    0.556909

[3 rows x 18056 columns]

In [26]:
gene_effect = gene_effect.transpose()
print(gene_effect)
gene_effect.to_csv('gene_effect.csv', index=True)

cell_line_name  RKI1_LD20  RKI1_LD90  RKI1_noT
gene
A1BG             0.525413   0.523391  0.518621
A1CF             0.092516   0.205165  0.262002
A2M             -0.137762  -0.018971  0.033230
A2ML1            0.431286   0.393950  0.342396
A3GALT2          0.118706   0.082567  0.315307
...                   ...        ...       ...
ZYG11B           0.214845   0.202745  0.108402
ZYX              0.136744   0.153242  0.324298
ZZEF1            0.479266   0.063136  0.203047
ZZZ3            -1.671247  -1.264286 -1.355150
luciferase       0.490876   0.392155  0.556909

[18056 rows x 3 columns]

In [27]:
lethal_score = pd.read_csv('lethal_score.csv', index_col = False)

In [28]:
print(lethal_score)

          gene  lethal_score
0         A1BG      0.046576
1         A1CF      0.045114
2          A2M      0.018318
3        A2ML1      0.010223
4      A3GALT2      0.102083
...        ...           ...
17926   ZYG11A      0.038951
17927   ZYG11B      0.115988
17928      ZYX      0.048788
17929    ZZEF1      0.088511
17930     ZZZ3      0.302026

[17931 rows x 2 columns]

In [29]:
new_gene_effect = lethal_score.merge(gene_effect, on='gene', how='right')
print (new_gene_effect)

             gene  lethal_score  RKI1_LD20  RKI1_LD90  RKI1_noT
0            A1BG      0.046576   0.525413   0.523391  0.518621
1            A1CF      0.045114   0.092516   0.205165  0.262002
2             A2M      0.018318  -0.137762  -0.018971  0.033230
3           A2ML1      0.010223   0.431286   0.393950  0.342396
4         A3GALT2      0.102083   0.118706   0.082567  0.315307
...           ...           ...        ...        ...       ...
18051      ZYG11B      0.115988   0.214845   0.202745  0.108402
18052         ZYX      0.048788   0.136744   0.153242  0.324298
18053       ZZEF1      0.088511   0.479266   0.063136  0.203047
18054        ZZZ3      0.302026  -1.671247  -1.264286 -1.355150
18055  luciferase           NaN   0.490876   0.392155  0.556909

[18056 rows x 5 columns]

In [30]:
new_gene_effect.to_csv('new_gene_effect.csv', index=True)

In [4]:
new_gene_effects = pd.read_csv("D:/Documents/Jayden Chronos test/new_gene_effect.csv", index_col = False)
print(new_gene_effects)

             gene  lethal_score  RKI1_LD20  RKI1_LD90  RKI1_noT
0            A1BG      0.046576   0.525413   0.523391  0.518621
1            A1CF      0.045114   0.092516   0.205165  0.262002
2             A2M      0.018318  -0.137762  -0.018971  0.033230
3           A2ML1      0.010223   0.431286   0.393950  0.342396
4         A3GALT2      0.102083   0.118706   0.082567  0.315307
...           ...           ...        ...        ...       ...
18051      ZYG11B      0.115988   0.214845   0.202745  0.108402
18052         ZYX      0.048788   0.136744   0.153242  0.324298
18053       ZZEF1      0.088511   0.479266   0.063136  0.203047
18054        ZZZ3      0.302026  -1.671247  -1.264286 -1.355150
18055  luciferase           NaN   0.490876   0.392155  0.556909

[18056 rows x 5 columns]

In [3]:
savedir = "D:/Documents/Jayden Chronos test/CRISPR_run"

model_restored = chronos.load_saved_model(savedir)

gene_effects = chronos.read_hdf5("D:/Documents/Jayden Chronos test/CRISPR_run/gene_effect.hdf5")
gene_effects.iloc[:4, :5]

Finding all unique guides and genes
found 71090 unique guides and 18056 unique genes in TKOv3
found 71090 unique guides and 18056 unique genes overall

finding guide-gene mapping indices

finding all unique sequenced replicates, cell lines, and pDNA batches
found 34 unique sequences (excluding pDNA) and 3 unique cell lines in TKOv3
found 34 unique replicates and 3 unique cell lines overall

finding replicate-cell line mappings indices

finding replicate-pDNA mappings indices


assigning float constants
Estimating or aligning variances
	Estimating excess variance (alpha) for TKOv3
Between 8 (batch=Index(['TKOv3_TKOv3_0'], dtype='object')) and 8 (batch=Index(['TKOv3_TKOv3_0'], dtype='object')) negative control sgRNAs were found to be systematically over- or under-represented in the screens and excluded.
Creating excess variance tensors
	Created excess variance tensor for TKOv3 with shape [34, 1]
initializing graph

building gene effect mask

building doubling vectors
made days vector of shape [34, 1] for TKOv3

building late observed timepoints
	built normalized timepoints for TKOv3 with shape (34, 71090) (replicates X guides)

building t0 reads


Building variables

building t0 reads estimate
made t0 batch with shape (1, 71090) for TKOv3
building guide efficacy
built guide efficacy: shape [1, 71091]
building growth rate
built growth rate: shape {'TKOv3': [3, 1]}

building cell line efficacy
built cell line efficacy: shapes {'TKOv3': [3, 1]}
building screen delay
built screen delay
building gene effect
built core gene effect: 3 cell lines by 18056 genes


Connecting graph nodes in model

building effective days
built effective days, shapes {'TKOv3': [34, 18056]}

building gene effect growth graph nodes
built gene effect growth graph nodes, shapes {'TKOv3': [3, 18056]}

building combined efficacy
built combined efficacy, shape {'TKOv3': [3, 71090]}
built expanded combined efficacy, shapes {'TKOv3': [34, 71090]}

building growth estimates of edited cells and overall estimates of fold change in guide abundance
built growth and change

building unnormalized estimates of final abundance
built unnormalized abundance

building normalized estimates of final abundance
built normalized abundance


Building all costs

assembling guide efficacy regularization
building smoothed regularization

building t0 reads regularization/cost

building NB2 cost
building other regularizations

Creating optimizer
initializing variables
	verifying graph integrity
verifying user inputs
verifying variables
verifying calculated terms
	TKOv3 _gene_effect
	TKOv3 _selected_efficacies
	TKOv3_predicted_readcounts_unscaled
	TKOv3 _predicted_readcounts
	TKOv3 _normalized_readcounts
	TKOv3 _cost_presum
sess run
	TKOv3 _cost
	TKOv3 _full_costs
ready to train
assigning trained parameters
	library effect
	gene effect
	guide efficacy
	cell efficacy
	cell growth rate
	screen excess variance
	screen delay
	t0 offset
Complete.
Cost when saved: 0.473613, cost now: 0.473613
Full cost when saved: 0.495922, full cost now: 0.495922

               A1BG      A1CF       A2M     A2ML1   A3GALT2
RKI1_LD20  0.389507  0.217222  0.125577  0.352046  0.227646
RKI1_LD90  0.388702  0.262055  0.172853  0.337187  0.213263
RKI1_noT   0.386804  0.284675  0.193628  0.316670  0.305889

In [4]:
gene_effects = gene_effects.transpose()
print(gene_effects)
gene_effects.to_csv('gene_effects.csv', index=True)

            RKI1_LD20  RKI1_LD90  RKI1_noT
A1BG         0.389507   0.388702  0.386804
A1CF         0.217222   0.262055  0.284675
A2M          0.125577   0.172853  0.193628
A2ML1        0.352046   0.337187  0.316670
A3GALT2      0.227646   0.213263  0.305889
...               ...        ...       ...
ZYG11B       0.265907   0.261091  0.223545
ZYX          0.234824   0.241390  0.309467
ZZEF1        0.371141   0.205530  0.261212
ZZZ3        -0.484720  -0.322758 -0.358920
luciferase   0.375762   0.336473  0.402042

[18056 rows x 3 columns]

In [10]:
gene_effect = pd.read_csv('gene_effects.csv', index_col = False)
lethal_score = pd.read_csv('lethal_score.csv', index_col = False)

In [44]:
print(lethal_score)
print(gene_effect)

          gene  lethal_score
0         A1BG      0.046576
1         A1CF      0.045114
2          A2M      0.018318
3        A2ML1      0.010223
4      A3GALT2      0.102083
...        ...           ...
17926   ZYG11A      0.038951
17927   ZYG11B      0.115988
17928      ZYX      0.048788
17929    ZZEF1      0.088511
17930     ZZZ3      0.302026

[17931 rows x 2 columns]
cell_line_name  RKI1_LD20  RKI1_LD90  RKI1_noT
gene
A1BG             0.525413   0.523391  0.518621
A1CF             0.092516   0.205165  0.262002
A2M             -0.137762  -0.018971  0.033230
A2ML1            0.431286   0.393950  0.342396
A3GALT2          0.118706   0.082567  0.315307
...                   ...        ...       ...
ZYG11B           0.214845   0.202745  0.108402
ZYX              0.136744   0.153242  0.324298
ZZEF1            0.479266   0.063136  0.203047
ZZZ3            -1.671247  -1.264286 -1.355150
luciferase       0.490876   0.392155  0.556909

[18056 rows x 3 columns]

In [45]:
new_gene_effects = lethal_score.merge(gene_effect, on='gene', how='right')
print (new_gene_effects)

             gene  lethal_score  RKI1_LD20  RKI1_LD90  RKI1_noT
0            A1BG      0.046576   0.525413   0.523391  0.518621
1            A1CF      0.045114   0.092516   0.205165  0.262002
2             A2M      0.018318  -0.137762  -0.018971  0.033230
3           A2ML1      0.010223   0.431286   0.393950  0.342396
4         A3GALT2      0.102083   0.118706   0.082567  0.315307
...           ...           ...        ...        ...       ...
18051      ZYG11B      0.115988   0.214845   0.202745  0.108402
18052         ZYX      0.048788   0.136744   0.153242  0.324298
18053       ZZEF1      0.088511   0.479266   0.063136  0.203047
18054        ZZZ3      0.302026  -1.671247  -1.264286 -1.355150
18055  luciferase           NaN   0.490876   0.392155  0.556909

[18056 rows x 5 columns]

In [13]:
new_gene_effects.to_csv('new_gene_effects.csv', index=True)

In [46]:
print (new_gene_effects)

             gene  lethal_score  RKI1_LD20  RKI1_LD90  RKI1_noT
0            A1BG      0.046576   0.525413   0.523391  0.518621
1            A1CF      0.045114   0.092516   0.205165  0.262002
2             A2M      0.018318  -0.137762  -0.018971  0.033230
3           A2ML1      0.010223   0.431286   0.393950  0.342396
4         A3GALT2      0.102083   0.118706   0.082567  0.315307
...           ...           ...        ...        ...       ...
18051      ZYG11B      0.115988   0.214845   0.202745  0.108402
18052         ZYX      0.048788   0.136744   0.153242  0.324298
18053       ZZEF1      0.088511   0.479266   0.063136  0.203047
18054        ZZZ3      0.302026  -1.671247  -1.264286 -1.355150
18055  luciferase           NaN   0.490876   0.392155  0.556909

[18056 rows x 5 columns]

In [106]:
print(rki1.sort_values(by='score', ascending=False).head(10)[['gene', 'score']])

         gene     score
16738  UGT1A5  0.204953
15706    TLN1  0.191872
213    ACTL6A  0.185181
12855  RBMXL1  0.179111
2985   CEP152  0.175783
12877    RCC2  0.172496
3604      CR2  0.169395
10310    NPM1  0.168175
16786    UPF1  0.167147
7056     HPCA  0.166879